feat: sparsed indexed merkle tree
trade-vex/vex-prover pull request #1
Opened 2024-12-26 20:18 UTC by esciiee

2024-12-31 09:07 UTC, rahulghangas requested changes
First pass done, will do one more after comments are addressed

2024-12-31 09:07 UTC, rahulghangas commented on src/components/insertions/mod.rs
Shouldn't public modules be included?

2024-12-31 09:07 UTC, rahulghangas commented on src/components/insertions/component.rs
An empty file should not included here

2024-12-31 09:07 UTC, rahulghangas commented on src/components/insertions/table.rs
> +
Empty space here, please run cargo fmt and do any relevant formatting on all files

2024-12-31 09:07 UTC, rahulghangas commented on src/components/mod.rs
Empty file

2024-12-31 09:07 UTC, rahulghangas commented on src/constants.rs
Can you add a comment on how the empty hashes were generated. Also, why do we need empty hashes? Shouldn't we use 0 values instead?

2024-12-31 09:07 UTC, rahulghangas commented on src/hash.rs
where was the hashing code taken from? Is it not possible to import it as a dependency rather than put it in the repo?

If this was taken from somewhere, we should attribute the original repo

2024-12-31 09:07 UTC, rahulghangas commented on src/imt/leaf.rs
> +    /// active leaf referes the node contains an order eligible to be executed
```suggestion
    /// active leaf indicate whether the node contains an order eligible to be executed
```

2024-12-31 09:07 UTC, rahulghangas commented on src/imt/mod.rs
> +    raw: Box<[Vec<Hash<BaseField>>]>,
Since the leaf is sparse now, why go for a boxed slice rather than vec, which will be owned here

2025-01-01 04:40 UTC, esciiee commented on src/components/insertions/mod.rs
the insertion module was included to show how the files would be structured for all the components, ill remove them and make another pr for inseretion circuit

2025-01-01 04:43 UTC, esciiee commented on src/hash.rs
This was taken from stwo, they were private functions so we ported it directly.
Other public repo's code was not generic to the field element. I'll add an attribution in the start of the file

2025-01-01 04:58 UTC, esciiee commented on src/imt/mod.rs
> +    raw: Box<[Vec<Hash<BaseField>>]>,
we can use a vec here, but since the tree's height is fixed, it is more idiomatic to use Box instead, we can consider [Vec<Hash<F>>; MERKLE_HEIGHT + 1], here we can avoid copying by using boxed slice

2025-01-01 05:03 UTC, esciiee commented on src/constants.rs
we can use 0 values but that would increase the degree of constraints atleast by 2 (inverse constraints for each field element) Using empty hashes is more efficient because the tree is assumed to be full and filled with empty leaves and the actual sparse structure of our tree would'nt affect our constraint system at all

2025-02-03 10:19 UTC, rahulghangas approved these changes

2025-02-03 10:19 UTC, merged